### ISSUE TITLE
CAST IPTV STREAM

### ISSUE THREAD

**Issue by ghost** [fanysoft/Android_CastMoviePlayer#1]
HI BRO
CAN YOU FIX PROBLEM TO CAST IPTV STREAM LINK?

**Comment by fanysoft** [comment]
@iptvdroid not sure what do you mean, is it "problem" in my app ?

**Comment by ghost** [comment]
NOT A PROBLEM ON YOUR APP , I JUST SEARCH A CODE TO CAST IPTV LINK TO ANDROID TV AND IF YOU CAN CONTACT ME HERE / zrigerezis1@gmail.com
